import { Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import MegaMenuNavbar from "@/components/layout/MegaMenuNavbar";
import Footer from "@/components/layout/Footer";
import { UserProvider } from '@/components/context/UserContext';
import { CartProvider } from '@/components/context/CartContext';
import { CategoryProvider } from '@/components/context/CategoryContext';
import CartToast from '@/components/cart/CartToast';
import CartSidebar from '@/components/cart/CartSidebar';
import CartFloating from '@/components/cart/CartFloating';
import ToastProvider from '@/components/ui/ToastProvider';



const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
  weight: ["100","200","300", "400", "500", "600", "700", "800"],
});

import LayoutWrapper from '@/components/layout/LayoutWrapper';
import ScrollToTop from "@/components/ui/ScrollToTop";
import FloatingWhatsApp from "@/components/ui/FloatingWhatsApp";
import PopupBanner from "@/components/ui/PopupBanner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${workSans.variable} antialiased`}>
        <UserProvider>
          <CartProvider>
            <CategoryProvider>
              <ScrollToTop/>
              <LayoutWrapper>
                {children}
              </LayoutWrapper>
              <FloatingWhatsApp/>
              {/* global UI overlays */}
              <CartToast />
              <CartSidebar />
              <CartFloating />
              <ToastProvider />
              <PopupBanner />
            </CategoryProvider>
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
