import { Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import { UserProvider } from '@/components/context/UserContext';
import { CartProvider } from '@/components/context/CartContext';
import CartToast from '@/components/cart/CartToast';
import CartSidebar from '@/components/cart/CartSidebar';
import CartFloating from '@/components/cart/CartFloating';



const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
  weight: ["100","200","300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${workSans.variable} antialiased`}>
        <UserProvider>
          <CartProvider>
            <Navbar />
            {children}
            <Footer />
            {/* global UI overlays */}
            <CartToast />
            <CartSidebar />
            <CartFloating />
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
